DROP DATABASE IF EXISTS game;
CREATE DATABASE game;
USE game;
CREATE TABLE scores (
given_id INT(11) NOT NULL AUTO_INCREMENT,
username VARCHAR (128) NOT NULL,
win INT (11) NOT NULL,
loss INT (11) NOT NULL,
tie INT (11) NOT NULL,
PRIMARY KEY (given_id)
) ENGINE=InnoDB;

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;
CREATE TABLE scores (
user_id INT(11) NOT NULL AUTO_INCREMENT,
username VARCHAR (128) NOT NULL,
win INT (11) NOT NULL,
loss INT (11) NOT NULL,
tie INT (11) NOT NULL,
PRIMARY KEY (user_id),
) ENGINE=InnoDB;
